spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources[0]:
            credential:
              client-id: a013e5ab-4c56-47a7-90aa-48df6e54bd02
              client-secret: sUI8Q~hCg0kH4yqkPGqlQQwvuIwZY-OU6tmPncf4
            profile:
              tenant-id: 1972f4ea-4dbc-4475-8204-536e6cd8a3ec
            endpoint: https://appservice-webapi-vault.vault.azure.net/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${jwkUri}
          issuer-uri: ${jwtIssuerUri}
          audience: ${webappAud}
azure:
  application-insights:
    instrumentation-key: ${appInsightInstrumentationKey}

